### ISSUE TITLE
Incompatibility with PSX.EXE games (and also NST errors?).

### ISSUE THREAD

**Issue by Webardo** [sahlberg/pop-fe#49] opened 2023-09-27 18:41 UTC
The following error is given when trying to convert "The Great Battle VI":

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 333, in on_path_changed
  File "pop-fe-psp.py", line 179, in update_assets
  File "pop-fe.py", line 168, in get_game_from_gamelist
KeyError: 'PSXEXE'

A similar issue also shows with the games "LEGO Rock Riders" (Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 333, in on_path_changed
  File "pop-fe-psp.py", line 179, in update_assets
  File "pop-fe.py", line 168, in get_game_from_gamelist
KeyError: 'NST')
 and "Santa Claus Saves the Earth" (Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 333, in on_path_changed
  File "pop-fe-psp.py", line 179, in update_assets
  File "pop-fe.py", line 168, in get_game_from_gamelist
KeyError: 'SLES04023').

**Comment by Snowbro88** [comment] 2023-09-28 05:16
The error present in The Great Battle VI is different from the one present in LEGO Rock Riders PAL and Santa Claus Saves the Earth PAL, these 2 games do contain the appropriate Game ID but this is what Pop Fe marks when selecting the game.
The Bin Cue images used are correct and have been verified with the CD Mage program.
I hope it can be reviewed and thank you very much for your incredible work, sorry for my English, I speak Spanish.

![Error en Pop FE Lego Rock Riders](https://github.com/sahlberg/pop-fe/assets/38197627/0e88ccf0-3381-400d-94e4-85c6bb4081b7)

**Comment by sahlberg** [comment] 2023-09-29 03:29
This is a duplicate of issue #48

**Comment by Webardo** [comment] 2023-09-30 01:22
I'm very sorry, but these 3 games still don't work. They still display the exact same error.

**Comment by sahlberg** [comment] 2023-09-30 02:49
Sorry, it was a slightly different issue.  This should be fixed now in the build at : 
https://github.com/sahlberg/pop-fe/actions/runs/6359676700

I have verified all three games with pop-fe-psp

**Comment by Webardo** [comment] 2023-09-30 03:15
It works for both "The Great Battle VI" and "Santa Claus Saves the World", but not for "Lego Rock Raiders".

I don't wish to keep pestering you however, try to check it if you feel like it, but if you don't it's fine too. So please forgive me for the trouble, and thanks for your attention :).

**Comment by sahlberg** [comment] 2023-09-30 03:49
That is fine. I want to fix it.
I tried LEGO Rock Raiders and it works here.   I tried with this one :
https://archive.org/download/redump.psx.p2/LEGO%20Rock%20Raiders%20%28Europe%29%20%28En%2CFr%2CDe%2CEs%2CIt%2CNl%2CSv%2CNo%2CDa%2CFi%29%20%28Rev%201%29.zip

Can you try that one?

**Comment by sahlberg** [comment] 2023-09-30 04:01
Also, can you try this version on the game that fails:
https://github.com/sahlberg/pop-fe/actions/runs/6360056391

I has extra debug information. Run it and paste a screenshot of what it prints in the console window.

**Comment by Webardo** [comment] 2023-09-30 04:12
This is what your debug build prints:
![Captura de pantalla (2)](https://github.com/sahlberg/pop-fe/assets/76268555/7c23b470-8f86-4137-adde-fe547b679783)

I did use the dump of the game you provided me.
Maybe the issue is in my system? I could try it on another computer to clear any doubts about that.

**Comment by sahlberg** [comment] 2023-09-30 04:31
Something is odd on your system.  It read SYSTEM.CNF but it treates it as a bytes object, not a string, it seems.
Can you try this build and paste what is prints
https://github.com/sahlberg/pop-fe/actions/runs/6360241431

**Comment by Webardo** [comment] 2023-09-30 04:39
![Captura de pantalla (82)](https://github.com/sahlberg/pop-fe/assets/76268555/1c48fc94-d189-4ffe-8eb1-531d26a644b6)

Weird thing is that this is a different system, yet the same error shows on both systems...

Maybe I'll just install linux haha.

**Comment by sahlberg** [comment] 2023-09-30 04:48
Linux is not bad,   but we need to ge tthis to work on windows too.

I think I have fixed it.
Can you try : 
 https://github.com/sahlberg/pop-fe/actions/runs/6360329784

**Comment by Webardo** [comment] 2023-09-30 05:01
Indeed you did! Seems good to go now. Thank you so much :).

**Closed** 2023-09-30 05:03 UTC

**Comment by sahlberg** [comment] 2023-09-30 05:19
Great.
Keep reporting bugs or games that have issues.
Every bug fix makes pop-fe better.
