### ISSUE TITLE
sound noize……

### ISSUE THREAD

**Issue by ghost** [sahlberg/pop-fe#14] opened 2022-08-18 06:32 UTC
title timecrisis
region japan

VITA 3.65

I used Tool of windows ver
Converted Audio is noisy
Compression ratio specification
Bitrate specification
Sampling specification
As a simple option to change the

I want you to add a function that can change these to windows ver

**Comment by japan1992** [comment] 2022-08-18 07:28
Sound quality and playback of XMB music is fine

Noise occurs when the converted cdda flows in the game

**Comment by sahlberg** [comment] 2022-08-18 07:34
It this the japanese version of TimeCrisis?
Is it a Japanese version of VITA ?

It could be a PAL/NTSC difference.
What is the GAME-ID/DISC-ID for the version of TimeCrisis you are using?
Is it SLPS-03188 ?  

I have a Japanese VITA. I can try to reproduce the issue on it.

**Comment by japan1992** [comment] 2022-08-18 07:38
title Time crisis
NTSC-J
region japan
disc  id SLPS-00666

**Comment by sahlberg** [comment] 2022-08-18 07:43
And you used POP-FE-PSP.EXE ?

**Comment by sahlberg** [comment] 2022-08-18 07:45
I think I know what the problem is. I will try to fix this tomorrow..

**Comment by japan1992** [comment] 2022-08-18 07:47
EBOOT.PBP
Used POP-FE-PSP.EXE to create in psp/game/

**Comment by japan1992** [comment] 2022-08-18 07:48
Thank You

**Comment by sahlberg** [comment] 2022-08-18 08:09
I think the problem is PAL/NTSC mismatch. The metadata for games contain a field to store the REGION/RESOLUTION of the game. And this is different between PAL (50Hz) and NTSC (60hz).
I fixed a bug for this already for POP-FE-PS3 but I never fixed it for PSP.

I think the bug is that when I create the EBOOT.PBP for PSP/VITA I hardcode these settings to always be "this is PAL" and it causes the issue. I need to change it to detect if it is an NTSC game and encode that "this is NTSC" instead.
This causes the timing for the music to be wrong and causes noice.

Can you try the European version of this game?   IF that version if the game as correct music then that proves my theory is right and that I know how to fix it.

**Comment by japan1992** [comment] 2022-08-18 10:50
I asked a friend to try SCES00657
Noise occurs on vita.…………
There seems to be a problem when converting cdda

**Comment by japan1992** [comment] 2022-08-18 12:36
[log.txt](https://github.com/sahlberg/pop-fe/files/9373832/log.txt)
Japanese version and PAL ver
the conversion result is the same........

my PC
win 8.1 
3740qm
ddr3 16gb

**Comment by japan1992** [comment] 2022-08-20 06:05
DISC SLPS03188
[log.txt](https://github.com/sahlberg/pop-fe/files/9386339/log.txt)

TITLE TIME CRISIS - PROJECT TITAN
japan

not sound
No music, just voice and sound effects
VITA 3.65
adrenaline v7

**Comment by phoe-nix** [comment] 2023-01-19 09:00
Same problem on PSP, if the game use CDDA tracks, all BGM cant play, just noise, tested on redump ISO.
the log doenst show converting CDDA.

**Comment by sahlberg** [comment] 2023-01-21 04:10
This only affects PSP and VITA. The root of the problem is that this is not well documented.
We know how to covert the audio files to ATRACK3 on PS3 and there is works well.
I thought that the audio was encoded the same way on PSP but it is not.
And there is little to no documentation available.

This needs a lot of reverse engineering so it may take a long time to fix.

**Comment by sahlberg** [comment] 2023-01-22 00:33
Can you try the artefact on this link? https://github.com/sahlberg/pop-fe/actions/runs/3977245379

I thought it was the ATRAC encoding that had issues so tryind to figure it out.
But it turns out it was the disc image itself.
I no longer store the raw audio tracks for cdda in the disk image but only the converted ATRAC3 audio and the noice is gone.

**Comment by sahlberg** [comment] 2023-01-22 00:54
Turns out the audio encoding was right all along but what happens is that the emulator tries to BOTH play the raw audio track (which is broken and causes noise) and also play the ATRAC3 encoded audio.
I now truncate the disc image so ONLY the first data track is stored inside the EBOOT.PBP and thus there are no longer any raw audio tracks for it to play and the noise is gone.

**Comment by sahlberg** [comment] 2023-01-22 07:33
This should be fixed now, please test.

**Comment by sahlberg** [comment] 2023-01-30 02:36
This should be fixed in the latest version and also the master branch.

**Closed by sahlberg** 2023-01-30 02:36 UTC

**Comment by sahlberg** [comment] 2023-02-05 00:42
Verified the fix with an audio spectrum analyzer. Using a 1000hz sine wave as SND0 and now it plays back at 1000hz on the xmb.
