### ISSUE TITLE
I'm getting a encoding error when using pop-fe on the command line

### ISSUE THREAD

**Issue by piegit** [sahlberg/pop-fe#47] opened 2023-09-27 08:30 UTC
It happens no matter what cue I use

`Traceback (most recent call last):
  File "pop-fe.py", line 2212, in <module>
  File "pop-fe.py", line 1523, in get_disc_ids
  File "bchunk.py", line 75, in open
  File "cue.py", line 82, in parse_cue
ValueError: substring not found
[7308] Failed to execute script 'pop-fe' due to unhandled exception!`

here's my command

`PS C:\Users\Mustacheboyo\Documents\Sony\Tools\pop-fe-ui> .\pop-fe.exe -v --title="Net Yaroze: Collection 2014-2019" --ga
me_id="NPEE78898, NPEE78899" --cover="C:\Users\Mustacheboyo\Documents\Sony\PS3\PS1_Classics\NetYaroze\ICON0.PNG" --pic0=
"C:\Users\Mustacheboyo\Documents\Sony\PS3\PS1_Classics\NetYaroze\PIC0.PNG" --pic1="C:\Users\Mustacheboyo\Documents\Sony\
PS3\PS1_Classics\NetYaroze\PIC1.PNG" --ps3-pkg="C:\Users\Mustacheboyo\Documents\Sony\PS3\PS1_Classics\NetYaroze\EP1337-N
PEE78900_00-NETYAROZE2014019.pkg" --whole-disk "C:\Users\Mustacheboyo\Documents\Sony\PS3\PS1_Classics\NetYaroze\CD [NET_
YAROZE_2014].bin" "C:\Users\Mustacheboyo\Documents\Sony\PS3\PS1_Classics\NetYaroze\CD [NET_YAROZE_2019].bin"`

I also tried crash team racing and I got the same result

**Comment by sahlberg** [comment] 2023-10-07 04:00
Can you try the build here:
https://github.com/sahlberg/pop-fe/actions/runs/6438836447

If that doesn't work I may need a copy of the bin/cue files to try to reproduce locally.
I don't really have access to a windows machine so fingers crossed it reproduces in linux.

**Comment by sahlberg** [comment] 2023-10-10 03:34
Ok, the problem is likely that as it is a NetYaroze disk  pop-fe can not match this to an entry in the database.
I have a dummy entry in the database for netyaroze so far.

To enable this, in the same directory as the cue file, create a file GAME_ID that should contain "NETY00001"
The file must be exactly 9 bytes big, so no blank line, no line-feed.

If that works we might want to start adding database entries for the netyaroze games that were published.
pull requests welcome :-)

**Comment by sahlberg** [comment] 2023-10-19 21:42
This should work better now as the scanning for disc id has been enhanced to deal with games like Sonic Wings and similar. Try latest build artefacts from the ACTIONs tab.
Closing for now.

**Closed by sahlberg** 2023-10-19 21:42 UTC
