### ISSUE TITLE
Sonic Wings Special [SLES-04102]

### ISSUE THREAD

**Issue by Fabax01** [sahlberg/pop-fe#56] opened 2023-10-18 02:01 UTC
```
Failed to read game id. Falling back to raw read
Traceback (most recent call last):
  File "/pop-fe/pop-fe.py", line 2449, in <module>
    game = get_game_from_gamelist(disc_ids[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pop-fe/pop-fe.py", line 189, in get_game_from_gamelist
    if 'url' not in games[game_id]:
                    ~~~~~^^^^^^^^^
KeyError: '         '
```

**Comment by sahlberg** [comment] 2023-10-18 04:33
This is addressed in current master.
The issue is that the ISO contained in the bin has what pycdlib considers invalid padding and it refuses to read from it.
On linux, this is now workaround by trying to use iso9660 module to read the disc id and that works.
Iso9660 is not available on windows so we can not detect what game it is there.

For now, I return a fake disc id 'UNKN00000' for this disk so that pop-fe will not throw an exception.
Since it is a fake disc-id  there will be no title and no art.

Optimally would be to send the ISO image to the pycdlib folks and see if they can see why their module refuses to open the iso and maybe add a workaround?

**Closed by sahlberg** 2023-10-18 04:33 UTC
